baseURL = "https://pearson-thaddeus-l.github.io/"
languageCode = "en-us"
title = "Thaddeus Pearson - IT Portfolio"
theme = "clarity"

[author]
  name  = "Thaddeus Pearson"
  email = "thaddeus@imap.cc"

[params]
  description = "IT Engineer | Systems | Linux | Automation"
  author = "Thaddeus Pearson"
  customCSS = ["css/neon.css"]
  showPostsOnHomepage = false
  mainSections = ["projects"]

[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Certifications"
    url  = "/certifications/"
    weight = 4

