baseURL = "https://pearson-thaddeus-l.github.io/"
languageCode = "en-us"
title = "Thaddeus Pearson - IT Engineer"
theme = "clarity"

[params]
  description = "IT Engineer | Systems | Cloud | Automation"
  themeVariant = "dark"
  customCSS = ["css/custom.css"]
