baseURL = "https://pearson-thaddeus-l.github.io/"
languageCode = "en-us"
title = "Thaddeus Pearson - I.T. Engineering Portfolio"
theme = "terminal"
pagination = 5

[markup.highlight]
  noClasses = false  # required by this theme
