baseURL = "https://pearson-thaddeus-l.github.io/"
languageCode = "en-us"
title = "Thaddeus Pearson"
theme = "terminal"
enableRobotsTXT = true
mainSections = ["posts"]

[markup.highlight]
  noClasses = false

[pagination]
  pagerSize = 10
